# 基础镜像
FROM jiftle/dev-env-gui:0.2

# 维护者
MAINTAINER jiftle "lixugood@126.com"

# ============== 变量定义==============
ARG INST_DIR="/instdir"

# ------------- 文件拷贝 -------------
# COPY files ${INST_DIR}

# ---------- 中文语言 ----------


# 清理临时文件
# RUN rm -rf ${INST_DIR}

# --------- 创建用户
# RUN addgroup -g 1000 john && adduser -u 1000 -D -h /home/john -G john john
# USER john

# 设置工作目录
# WORKDIR /home/john
WORKDIR /root
